language: node_js
node_js:
  - "10.15.2"
script:
  - echo "Deploying"
install:
  - npm install -g firebase-tools
  - npm install -g @vue/cli-service-global
after_success:  
  - npm run build
  - firebase deploy --token $FKEY

  #  - npm install -g vue-cli
  # - npm install vue